spring:
  config:
    activate:
      on-profiles: test
  mvc:
    pathmatch:
      matching-strategy: ant_path_matcher
  datasource:
    driver-class-name: org.h2.Driver
  jpa:
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        default_batch_fetch_size: 1000
        format_sql: true
        show_sql: true
        dialect: org.hibernate.dialect.H2Dialect